calculator_token_link = "https://wynagrodzenia.pl/kalkulator-wynagrodzen"
calculator_link = "https://wynagrodzenia.pl/kalkulator-wynagrodzen/wyniki"
form_data = {
    "sedlak_calculator[contractType]": "work",
    "sedlak_calculator[calculateWay]": "gross",
    "sedlak_calculator[earnings]": "",
    "sedlak_calculator[year]": "2021",
    "sedlak_calculator[mandateModels]": "otherCompany",
    "sedlak_calculator[theSameCity]": "1",
    "sedlak_calculator[freeCost]": "1",
    "sedlak_calculator[constantEarnings]": "1",
    "work_end26Year": "on",
    "sedlak_calculator[monthlyEarnings][0]": "",
    "sedlak_calculator[monthlyEarnings][1]": "",
    "sedlak_calculator[monthlyEarnings][2]": "",
    "sedlak_calculator[monthlyEarnings][3]": "",
    "sedlak_calculator[monthlyEarnings][4]": "",
    "sedlak_calculator[monthlyEarnings][5]": "",
    "sedlak_calculator[monthlyEarnings][6]": "",
    "sedlak_calculator[monthlyEarnings][7]": "",
    "sedlak_calculator[monthlyEarnings][8]": "",
    "sedlak_calculator[monthlyEarnings][9]": "",
    "sedlak_calculator[monthlyEarnings][10]": "",
    "sedlak_calculator[monthlyEarnings][11]": "",
    "sedlak_calculator[selfEmployer]": "1",
    "sedlak_calculator[rentAndAnnuityCost]": "1",
    "sedlak_calculator[sicknesCost]": "1",
    "sedlak_calculator[healthCost]": "1",
    "sedlak_calculator[FPCost]": "1",
    "sedlak_calculator[FGSPCost]": "1",
    "mandate_end26Year": "on",
    "sedlak_calculator[accidentPercent]": "1.67",
    "sedlak_calculator[end26Year]": "1",
    "sedlak_calculator[employeePercent]": "2",
    "sedlak_calculator[employerPercent]": "1.5",
    "sedlak_calculator[octoberIncome]": "1",
    "sedlak_calculator[businessExpenses]": "0",
    "work_accidentPercent": "1.67",
    "nonwork_accidentPercent": "1.67",
    "sedlak_calculator[save]": "",
    "sedlak_calculator[_token]": ""
}